apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: node-red-app
  name: node-red-app
spec:
  ports:
  - protocol: TCP
    nodePort: 32323
    port: 3000
    targetPort: 3000
  selector:
    app: node-red-app
  type: NodePort
status:
  loadBalancer: {}
